version: '3.7'

services:
  lb:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - one-api
      - one-api-slave
  one-api:
    image: ahhhliu/one-api:latest-amd64
    platform: "linux/amd64"
    restart: always
    command: --log-dir /app/logs
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "4001:3000"
      - "8899:8899"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 300M
  one-api-slave:
    image: ahhhliu/one-api:latest-amd64
    platform: "linux/amd64"
    restart: always
    command: --log-dir /app/logs
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "4002:3000"
      - "18899:8899"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_TYPE=slave
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 250M
      replicas: 1
      restart_policy:
        condition: on-failure
  redis:
    image: redis:latest
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: unless-stopped