version: '3.4'

services:
  one-api:
    build: ./
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
#    ports:
#      - "4000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - PORT=4000
      - SQL_DSN=oneapi:h4jLCeLR4eCPkTZf@tcp(localhost:3306)/oneapi  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://localhost
      - SESSION_SECRET=random_string  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
#    depends_on:
#      - redis
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -s http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk '{print $2}' | grep 'true'" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#
#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: always
