version: '3.4'

services:
  one-api:
    image: ahhhliu/one-api:latest
    restart: always
    command: --log-dir /app/logs
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING="redis://redis:6379/0"
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    restart: always
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: unless-stopped