version: '3.7'

services:
  one-api:
    image: ahhhliu/one-api:latest
    restart: always
    command: --log-dir /app/logs
    ports:
      - "4000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 200M
  one-api-slave:
    image: ahhhliu/one-api:latest
    restart: always
    command: --log-dir /app/logs
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_TYPE=slave
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 150M
      replicas: 2
      restart_policy:
        condition: on-failure
  lb:
    image: nginx:alpine
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        - one-api
        - one-api-slave
  redis:
    image: redis:latest
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: unless-stopped